/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.cliente;

public interface CadastrosClienteConstants {
	
	String DOMAIN = "cadastros";
	String SERVICE = "cliente";
	
	interface Events {
		
	}

}
