/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.cliente.entity.compromisso;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class CompromissoAutoCompleteImpl implements CompromissoAutoComplete {

	private java.util.UUID id;
	
	private String titulo;
	
	public CompromissoAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
