/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.cliente.entity.compromisso;

import org.springframework.util.CollectionUtils;

import org.springframework.stereotype.Component;
import com.querydsl.core.types.Predicate;
import com.querydsl.core.BooleanBuilder;
import com.querydsl.core.types.dsl.BooleanExpression;

@Component
public class CompromissoListFilterPredicateImpl implements CompromissoListFilterPredicate {
	
	@Override
	public Predicate mountAndGetPredicate(CompromissoListFilter compromissoListFilter) {
		if (compromissoListFilter == null) {
			return null;
		}
		
		QCompromissoEntity qEntity = QCompromissoEntity.compromissoEntity;
		BooleanBuilder where = new BooleanBuilder();
		
		// Begin field: titulo
		if (!CollectionUtils.isEmpty(compromissoListFilter.getTitulo())) {
			BooleanExpression inExpression = qEntity.titulo.in(compromissoListFilter.getTitulo());
			where.and(inExpression);
		}
		// End field: titulo
		
		return where;
	}

}

