/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.cliente.entity.compromisso;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.transaction.annotation.Transactional;
import java.util.Collection;
import org.springframework.data.repository.query.Param;

@Transactional(readOnly = true)
public interface CompromissoRepository extends JpaRepository<CompromissoEntity, java.util.UUID>, QuerydslPredicateExecutor<CompromissoEntity> {
	
	@Transactional
	@Modifying
	@Query("delete from CompromissoEntity ce where ce.id in ?1")
	void deleteInBulk(java.util.List<java.util.UUID> idList);
	
	
	// WARNING: supports only where clause with like for STRING fields. For relationships entities will get the first string autocomplete key field name.
	@Query("select distinct ac.id as id, ac.titulo as titulo from CompromissoEntity ac where ( upper(unaccent(ac.titulo)) like upper(concat('%', unaccent(:query), '%')) ) order by 1 asc")
	Collection<CompromissoAutoComplete> autoComplete(@Param("query") String query);
	
	// WARNING: supports only where clause with like for STRING fields. For relationships entities will get the first string autocomplete key field name.
	@Query("select distinct ac.titulo as titulo from CompromissoEntity ac where ( upper(unaccent(ac.titulo)) like upper(concat('%', unaccent(:query), '%')) ) order by 1 asc")
	Collection<CompromissoTituloAutoComplete> compromissoTituloAutoComplete(@Param("query") String query);
}
