/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.cliente.entity.compromisso;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import br.com.kerubin.api.cadastros.cliente.entity.cliente.ClienteLookupResult;
import javax.validation.constraints.NotNull;
import br.com.kerubin.api.cadastros.cliente.CompromissoSituacao;
import br.com.kerubin.api.cadastros.cliente.entity.recurso.RecursoLookupResult;

public class Compromisso {

	private java.util.UUID id;
	
	@NotBlank(message="\"Título\" é obrigatório.")
	@Size(max = 255, message = "\"Título\" pode ter no máximo 255 caracteres.")
	private String titulo;
	
	private ClienteLookupResult cliente;
	
	@NotNull(message="\"Data de início\" é obrigatório.")
	private java.time.LocalDate dataIni;
	
	@NotNull(message="\"Hora de início\" é obrigatório.")
	private java.time.LocalTime horaIni;
	
	private java.time.LocalDate dataFim;
	
	private java.time.LocalTime horaFim;
	
	private Boolean diaTodo = false;
	
	@NotNull(message="\"Situação\" é obrigatório.")
	private CompromissoSituacao situacao;
	
	@Size(max = 1000, message = "\"Descrição\" pode ter no máximo 1000 caracteres.")
	private String descricao;
	
	@Size(max = 255, message = "\"Local\" pode ter no máximo 255 caracteres.")
	private String local;
	
	private java.util.Set<RecursoLookupResult> recursos;
	
	@Size(max = 255, message = "\"Criado por\" pode ter no máximo 255 caracteres.")
	private String createdBy;
	
	private java.time.LocalDateTime createdDate;
	
	@Size(max = 255, message = "\"Alterado por\" pode ter no máximo 255 caracteres.")
	private String lastModifiedBy;
	
	private java.time.LocalDateTime lastModifiedDate;
	
	
	public Compromisso() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}
	
	
	public java.util.UUID getId() {
		return id;
	}
	
	public String getTitulo() {
		return titulo;
	}
	
	public ClienteLookupResult getCliente() {
		return cliente;
	}
	
	public java.time.LocalDate getDataIni() {
		return dataIni;
	}
	
	public java.time.LocalTime getHoraIni() {
		return horaIni;
	}
	
	public java.time.LocalDate getDataFim() {
		return dataFim;
	}
	
	public java.time.LocalTime getHoraFim() {
		return horaFim;
	}
	
	public Boolean getDiaTodo() {
		return diaTodo;
	}
	
	public CompromissoSituacao getSituacao() {
		return situacao;
	}
	
	public String getDescricao() {
		return descricao;
	}
	
	public String getLocal() {
		return local;
	}
	
	public java.util.Set<RecursoLookupResult> getRecursos() {
		return recursos;
	}
	
	public String getCreatedBy() {
		return createdBy;
	}
	
	public java.time.LocalDateTime getCreatedDate() {
		return createdDate;
	}
	
	public String getLastModifiedBy() {
		return lastModifiedBy;
	}
	
	public java.time.LocalDateTime getLastModifiedDate() {
		return lastModifiedDate;
	}
	
	public void setId(java.util.UUID id) {
		this.id = id;
	}
	
	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}
	
	public void setCliente(ClienteLookupResult cliente) {
		this.cliente = cliente;
	}
	
	public void setDataIni(java.time.LocalDate dataIni) {
		this.dataIni = dataIni;
	}
	
	public void setHoraIni(java.time.LocalTime horaIni) {
		this.horaIni = horaIni;
	}
	
	public void setDataFim(java.time.LocalDate dataFim) {
		this.dataFim = dataFim;
	}
	
	public void setHoraFim(java.time.LocalTime horaFim) {
		this.horaFim = horaFim;
	}
	
	public void setDiaTodo(Boolean diaTodo) {
		this.diaTodo = diaTodo;
	}
	
	public void setSituacao(CompromissoSituacao situacao) {
		this.situacao = situacao;
	}
	
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
	public void setLocal(String local) {
		this.local = local;
	}
	
	public void setRecursos(java.util.Set<RecursoLookupResult> recursos) {
		this.recursos = recursos;
	}
	
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	
	public void setCreatedDate(java.time.LocalDateTime createdDate) {
		this.createdDate = createdDate;
	}
	
	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}
	
	public void setLastModifiedDate(java.time.LocalDateTime lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Compromisso other = (Compromisso) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		
		return true;
	}
	
	@Override
	public int hashCode() {
		return 31;
	}
	
	/* 
	@Override
	public String toString() {
		// Enabling toString for JPA entities will implicitly trigger lazy loading on all fields.
	}
	*/

}
