/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.cliente.entity.compromisso;



public interface CompromissoAutoComplete {

	java.util.UUID getId();
	
	String getTitulo();
	
	void setId(java.util.UUID id);
	
	void setTitulo(String titulo);

}
