/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


package br.com.kerubin.api.cadastros.cliente.entity.recurso;

import javax.inject.Inject;
import org.springframework.stereotype.Component;
import br.com.kerubin.api.servicecore.mapper.ObjectMapper;

@Component
public class RecursoDTOConverter {

	@Inject
	private ObjectMapper mapper;

	public Recurso convertEntityToDto(RecursoEntity entity) {
		Recurso dto = null;
		if (entity != null) {
			dto = mapper.map(entity, Recurso.class, true); // Do not permit passwords fields go outside.
		}
		return dto;
	}


	public RecursoEntity convertDtoToEntity(Recurso dto) {
		RecursoEntity entity = null;
		if (dto != null) {
			entity = mapper.map(dto, RecursoEntity.class);
		}
		return entity;
	}


}