/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.cliente.entity.recurso;

import lombok.Getter;
import lombok.Setter;

@Getter @Setter
public class RecursoAutoCompleteImpl implements RecursoAutoComplete {

	private java.util.UUID id;
	
	private String nome;
	
	private String email;
	
	public RecursoAutoCompleteImpl() {
		// Contructor for reflexion, injection, Jackson, QueryDSL, etc proposal.
	}

}
