/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.cliente.entity.recurso;

import org.springframework.web.bind.annotation.RequestParam;
import java.util.List;
import java.util.stream.Collectors;

import javax.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.http.ResponseEntity;
import org.springframework.http.HttpStatus;

import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.DeleteMapping;

import br.com.kerubin.api.cadastros.cliente.common.PageResult;

import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

@RestController
@RequestMapping("cadastros/cliente/entities/recurso")
public class RecursoController {
	
	@Autowired
	private RecursoService recursoService;
	
	@Autowired
	RecursoDTOConverter recursoDTOConverter;
	
	@Transactional
	@PostMapping
	public ResponseEntity<Recurso> create(@Valid @RequestBody Recurso recurso) {
		RecursoEntity recursoEntity = recursoService.create(recursoDTOConverter.convertDtoToEntity(recurso));
		return ResponseEntity.status(HttpStatus.CREATED).body(recursoDTOConverter.convertEntityToDto(recursoEntity));
	}
	
	@Transactional(readOnly = true)
	@GetMapping("/{id}")
	public ResponseEntity<Recurso> read(@PathVariable java.util.UUID id) {
		try {
			RecursoEntity recursoEntity = recursoService.read(id);
			return ResponseEntity.ok(recursoDTOConverter.convertEntityToDto(recursoEntity));
		}
		catch(IllegalArgumentException e) {
			return ResponseEntity.notFound().build();
		}
	}
	
	@Transactional
	@PutMapping("/{id}")
	public ResponseEntity<Recurso> update(@PathVariable java.util.UUID id, @Valid @RequestBody Recurso recurso) {
		try {
			RecursoEntity recursoEntity = recursoService.update(id, recursoDTOConverter.convertDtoToEntity(recurso));
			return ResponseEntity.ok(recursoDTOConverter.convertEntityToDto(recursoEntity));
		}
		catch(IllegalArgumentException e) {
			return ResponseEntity.notFound().build();
		}
	}
	
	@ResponseStatus(HttpStatus.NO_CONTENT)
	@DeleteMapping("/{id}")
	public void delete(@PathVariable java.util.UUID id) {
		recursoService.delete(id);
	}
	
	@ResponseStatus(HttpStatus.NO_CONTENT)
	@PostMapping("/deleteInBulk")
	public void deleteInBulk(@RequestBody java.util.List<java.util.UUID> idList) {
		recursoService.deleteInBulk(idList);
	}
	
	@Transactional(readOnly = true)
	@GetMapping
	public PageResult<Recurso> list(RecursoListFilter recursoListFilter, Pageable pageable) {
		Page<RecursoEntity> page = recursoService.list(recursoListFilter, pageable);
		List<Recurso> content = page.getContent().stream().map(pe -> recursoDTOConverter.convertEntityToDto(pe)).collect(Collectors.toList());
		PageResult<Recurso> pageResult = new PageResult<>(content, page.getNumber(), page.getSize(), page.getTotalElements());
		return pageResult;
	}
	
	@Transactional(readOnly = true)
	@GetMapping("/autoComplete")
	public Collection<RecursoAutoComplete> autoComplete(@RequestParam("query") String query) {
		Collection<RecursoAutoComplete> result = recursoService.autoComplete(query);
		return result;
	}
	
	
	@GetMapping("/recursoNomeAutoComplete")
	public Collection<RecursoNomeAutoComplete> recursoNomeAutoComplete(@RequestParam("query") String query) {
		Collection<RecursoNomeAutoComplete> result = recursoService.recursoNomeAutoComplete(query);
		return result;
	}
	
	
}
