/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.cliente.entity.recurso;

import org.springframework.util.CollectionUtils;

import org.springframework.stereotype.Component;
import com.querydsl.core.types.Predicate;
import com.querydsl.core.BooleanBuilder;
import com.querydsl.core.types.dsl.BooleanExpression;

@Component
public class RecursoListFilterPredicateImpl implements RecursoListFilterPredicate {
	
	@Override
	public Predicate mountAndGetPredicate(RecursoListFilter recursoListFilter) {
		if (recursoListFilter == null) {
			return null;
		}
		
		QRecursoEntity qEntity = QRecursoEntity.recursoEntity;
		BooleanBuilder where = new BooleanBuilder();
		
		// Begin field: nome
		if (!CollectionUtils.isEmpty(recursoListFilter.getNome())) {
			BooleanExpression inExpression = qEntity.nome.in(recursoListFilter.getNome());
			where.and(inExpression);
		}
		// End field: nome
		
		return where;
	}

}

