/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

package br.com.kerubin.api.cadastros.cliente.entity.recurso;

import java.util.Collection;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;


public interface RecursoService {
	
	public RecursoEntity create(RecursoEntity recursoEntity);
	
	public RecursoEntity read(java.util.UUID id);
	
	public RecursoEntity update(java.util.UUID id, RecursoEntity recursoEntity);
	
	public void delete(java.util.UUID id);
	
	public void deleteInBulk(java.util.List<java.util.UUID> idList);
	
	public Page<RecursoEntity> list(RecursoListFilter recursoListFilter, Pageable pageable);
	
	public Collection<RecursoAutoComplete> autoComplete(String query);
	
	 
	
	public Collection<RecursoNomeAutoComplete> recursoNomeAutoComplete(String query);
}
